import { DocsLayout } from "fumadocs-ui/layouts/docs";
import Link from "next/link";
import type { Metadata } from "next";
import { docsLayoutProps } from "@/lib/layout.shared";
import { listArtifacts } from "@/lib/artifacts";

export const metadata: Metadata = {
  title: "Artifacts",
  description: "Standalone HTML pages generated by skills, browsable here.",
};

export default async function ArtifactsPage() {
  const byType = await listArtifacts();
  const types = Object.keys(byType).sort();
  return (
    <DocsLayout {...await docsLayoutProps()}>
      <main className="mx-auto w-full max-w-3xl flex-1 px-6 py-10">
        <h1 className="mb-2 text-3xl font-semibold">Artifacts</h1>
        <p className="text-fd-muted-foreground mb-8">
          Standalone pages generated by skills, served with their own chrome.
        </p>
        {types.length === 0 ? (
          <p className="text-fd-muted-foreground text-sm">(none yet)</p>
        ) : (
          types.map((type) => (
            <section key={type} className="mb-8">
              <h2 className="mb-3 text-xl font-semibold">{type}</h2>
              <ul className="space-y-2">
                {byType[type].map((a) => (
                  <li key={a.file}>
                    <Link
                      href={`/artifacts/view/${type}/${a.file}`}
                      className="font-medium underline"
                    >
                      {a.name}
                    </Link>
                  </li>
                ))}
              </ul>
            </section>
          ))
        )}
      </main>
    </DocsLayout>
  );
}
